config/routes.rb
Rails.application.routes.draw do
  get 'my-sales', to: 'equipments#sale'
  get 'my-listings', to: 'equipments#list'

  resources :equipments, only: [:index, :show, :create, :new] do
    resources :rentals, only: [:new, :create] # nested in controller?
  end

  resources :rentals, only: [:index]
  devise_for :users
  root to: 'equipments#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

# root to admin?
# devise_for :users?

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :user
  has_many :rentals, dependent: :destroy
  before_destroy :purge_photo
  has_many :rentals

  has_one_attached :photo

  validates :name, :description, :price_per_day, presence: true
  validates :price_per_day, numericality: { only_integer: true, greater_than: 0 }
  validates :category, inclusion: { in: %w[Gym Racket Camping],
    message: "%{value} is not one of three categories" }

  include PgSearch::Model
  pg_search_scope :search_by_equipment,
  against: %i[name description],
  using: {
    tsearch: { prefix: true }
  }

  def unavailable_dates
    rentals.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end

  private

  def purge_photo
    photo.purge
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :equipment
  belongs_to :user

  validate :end_date_before_start_date

  def end_date_before_start_date
    return errors.add(:end_date, "must be after the start date") if end_date < start_date
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :equipments, dependent: :destroy

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username, photo])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username, photo])
  end
end

app/controllers/equipments_controller.rb
require 'open-uri'

class EquipmentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query]
      @equipments = Equipment.search_by_equipment(params[:query]).order(updated_at: :desc)
    else
      @equipments = Equipment.all.order(updated_at: :desc)
    end
  end

  def show
    @equipment = Equipment.find(params[:id])
  end

  def new
    @user = current_user
    @equipment = Equipment.new
  end

  def create
    @equipment = Equipment.new(equipment_params)
    @equipment.user = current_user
    @equipment.price_per_day *= 100

    if @equipment.save
      if equipment_params[:photo].nil?
        query = @equipment.name.split.join(',')
        url = "https://source.unsplash.com/720x480/?#{query}"
        image = URI.parse(url).open
        @equipment.photo.attach(io: image, filename: "equipment_#{@equipment.id}.jpeg", content_type: 'image/jpeg')
      end
      redirect_to equipment_path(@equipment)
    else
      render :new
    end
  end

  def list
    @equipment = Equipment.where(user: current_user).order(updated_at: :desc)
  end

  def sale
    today = Date.today
    @rentals = Rental.where(equipment: Equipment.where(user: current_user)).order(end_date: :desc)
    @future_rentals = @rentals.where("start_date > ?", today)
    @past_rentals = @rentals.where("end_date < ?", today)
    @current_rentals = @rentals.where("start_date <= ? AND end_date >= ?", today, today)
  end

  private

  def equipment_params
    params.require(:equipment).permit(:name, :description, :category, :price_per_day, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  # this is all rentals here current user = user
  def index
    today = Date.today
    @rentals = Rental.where(user: current_user).order(end_date: :desc)
    @future_rentals = @rentals.where("start_date > ?", today)
    @past_rentals = @rentals.where("end_date < ?", today)
    @current_rentals = @rentals.where("start_date <= ? AND end_date >= ?", today, today)
  end

  def new
    @equipment = Equipment.find(params[:equipment_id])
    @user = current_user
    @rental = Rental.new
  end

  def create
    @rental = Rental.new(rental_params)
    @rental.user = current_user
    @rental.equipment = Equipment.find(params[:equipment_id])
    days = (@rental.end_date - @rental.start_date).to_i + 1
    price_per_day = @rental.equipment.price_per_day
    @rental.price = price_per_day * days
    if @rental.save
      redirect_to rentals_path
    else
      render :new
    end
  end

  private

  def rental_params
    params.require(:rental).permit(:start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/equipments/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://secureprintportal.s3.us-west-1.amazonaws.com/production/assets/5966561450122033bd4456f8/imageLocker/blog-description/5f11c366a53d4d3a831471de/blog/sports_banners.png);">
  <div class="container">
    <h1>Your <strong>Passport</strong> to <strong>all Sports</strong></h1>
    <p>Play anything, we've got you</p>


  </div>
</div>

<div class = "mt-4">
  <h2><strong>Explore Listings</strong></h2>
</div>
  <% @equipments.each do |equipment| %>
    <%= link_to equipment_path(equipment) do %>
      <div class = "card-main my-4">
        <div class="card-product">
           <%= cl_image_tag equipment.photo.key, crop: :fill, class: "product-image" %>
            <div class="card-product-infos">
              <h4><%= equipment.name %></h4>
              <p>$<strong><%= equipment.price_per_day / 100 %></strong> per day</p>
            </div>
          <div class='card-username'>
            <%= equipment.user.username unless equipment.user.username.nil? %>
            <% if equipment.user.photo.attached? %>
            <%= cl_image_tag equipment.user.photo.key, height: 50, width: 50, crop: :fill, class: "avatar-small" %>
            <% else %>
            <%= image_tag "https://www.flaticon.com/svg/static/icons/svg/599/599305.svg", height: 50, width: 50, crop: :fill, class: "avatar-small" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

app/views/equipments/list.html.erb
<h1>My Equipments listed for Rental</h1>

<div class="row">
  <div class="col-sm-12 col-md-12">

    <h3>Current List</h3>
      <% if @equipment.exists? %>
        <% @equipment.each do |e| %>
          <div class = "my-4">
            <div class="card-product">
              <%= cl_image_tag e.photo.key, crop: :fill, class: "product-image" %>
              <div class="card-product-infos">
                <h6><strong><%= e.name %></strong></h6>
                <p><%= e.description %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
          <div class = "my-4">
            <div class="card-product">
              <div class="card-product-infos">
                <h6><strong>You have no listings for rental</strong></h6>
              </div>
            </div>
          </div>
      <% end %>

    </div>
</div>

app/views/equipments/new.html.erb
 <div class="container col-6">
  <h2 class='mt-3'><strong>Add New Equipment!</strong></h2>
  <div class='form-login mt-0'>

    <%= simple_form_for(@equipment, as: :equipment, method: :post, url: equipments_path, remote: true ) do |f| %>
     <%= f.input :name %>
     <%= f.input :description %>
     <%= f.input :category, collection: %w(Gym Racket Camping) %>
     <%= f.input :price_per_day, label: 'Price per Day in $' %>
     <%= f.input :photo, as: :file %>
     <%= f.submit "Post", class: "btn btn-primary" %>
     <% end %>
  </div>
</div>

app/views/equipments/sale.html.erb
<div class="container col-10">
  <h1>Sales of My Equipment</h1>

  <div class="row">
    <div class="col-sm-12 col-md-12">

      <h3>Current Rentals</h3>
        <% if @current_rentals.exists? %>
          <% @current_rentals.each do |rental| %>
            <div class = "my-4">
              <div class="card-product">
                <%= cl_image_tag rental.equipment.photo.key, crop: :fill, class: "product-image" %>
                <div class="card-product-infos">
                  <h6><strong><%= rental.equipment.name %></strong></h6>
                  <h6><strong>Rental Period:</strong></h6>
                  <p><%= "#{rental.start_date.strftime('%d-%b-%Y')} to #{rental.end_date.strftime('%d-%b-%Y')}" %></p>
                  <h6><strong>Rented By:</strong></h6>
                  <p><%= rental.user.username %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
            <div class = "my-4">
              <div class="card-product">
                <div class="card-product-infos">
                  <h6><strong>There are no active rentals ongoing.</strong></h6>
                </div>
              </div>
            </div>
        <% end %>

      <h3>Future Rentals</h3>
        <% if @future_rentals.exists? %>
          <% @future_rentals.each do |rental| %>
            <div class = "my-4">
              <div class="card-product">
                <%= cl_image_tag rental.equipment.photo.key, crop: :fill, class: "product-image" %>
                <div class="card-product-infos">
                  <h5><strong><%= rental.equipment.name %></strong></h5>
                  <p><strong>Rental Period:</strong>
                  <%= "#{rental.start_date.strftime('%d %b %Y')} to #{rental.end_date.strftime('%d %b %Y')}" %></p>
                  <p><strong>Rented By:</strong>
                  <%= rental.user.username %></p>
                  <p><strong>Total Price:</strong>
                  $<%= rental.price / 100 %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
            <div class = "my-4">
              <div class="card-product">
                <div class="card-product-infos">
                  <h6><strong>There are no upcoming bookings.</strong></h6>
                </div>
              </div>
            </div>
        <% end %>

        <h3>Past Rentals</h3>
        <% if @past_rentals.exists? %>
          <% @past_rentals.each do |rental| %>
            <div class = "my-4">
              <div class="card-product">
                <%= cl_image_tag rental.equipment.photo.key, crop: :fill, class: "product-image" %>
                <div class="card-product-infos">
                  <h6><strong><%= rental.equipment.name %></strong></h6>
                  <h6><strong>Rental Period:</strong></h6>
                  <p><%= "#{rental.start_date.strftime('%d-%b-%Y')} to #{rental.end_date.strftime('%d-%b-%Y')}" %></p>
                  <h6><strong>Rented By:</strong></h6>
                  <p><%= rental.user.username %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <div class = "my-4">
            <div class="card-product">
              <div class="card-product-infos">
                <h6><strong>There are no past bookings.</strong></h6>
              </div>
            </div>
          </div>
        <% end %>

      </div>
  </div>
</div>

app/views/equipments/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-8 col-m-4">
      <%= cl_image_tag @equipment.photo.key, crop: :fill, width: 640, height: 420 %>
    </div>
    <div class="col-12 col-lg-4 col-m-2">
      <table class="table" >
        <tbody>
          <tr>
            <h3><%= @equipment.name %></h3>
            <p><%= @equipment.description %></p>
            <th>Price</th>
            <td>$<%= @equipment.price_per_day / 100 %></td>
          </tr>
        </tbody>
      </table>
        <div>
          <%= link_to "Rent", new_equipment_rental_path(@equipment), class: 'btn btn-primary mb-3' %>
          <%= link_to "Back to Listing", equipments_path, class: 'btn btn-primary mb-3' %>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PassSports</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/airbnb.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container my-2">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/rentals/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://secureprintportal.s3.us-west-1.amazonaws.com/production/assets/5966561450122033bd4456f8/imageLocker/blog-description/5f11c366a53d4d3a831471de/blog/sports_banners.png);">
  <div class="container">
    <h1> <strong>Your Rentals</strong></h1>
  </div>
</div>

<div class="row">
  <div class="col-sm-12 col-md-12">

    <div class = "mt-4">
      <h3>Current Rentals</h3>
    </div>
      <% if @current_rentals.exists? %>
        <%# <h3>Current Rental</h3> %>
        <% @current_rentals.each do |rental| %>

          <div class = "my-4">
            <div class="card-product">
              <%= cl_image_tag rental.equipment.photo.key, crop: :fill, class: "product-image" %>
              <div class="card-product-infos">
                <h6><strong>Rental Period:</strong></h6>
                <p><%= "#{rental.start_date.strftime('%d-%b-%Y')} to #{rental.end_date.strftime('%d-%b-%Y')}" %></p>
              </div>
            </div>
          </div>
        <% end %>

      <% else %>
          <div class = "my-4">
            <div class="card-product">
              <div class="card-product-infos">
                <h6><strong>There are no active rentals ongoing</strong></h6>
              </div>
            </div>
          </div>
      <% end %>

    <h3>Future Rentals</h3>
      <% if @future_rentals.exists? %>
        <%# <h3>Current Rental</h3> %>
        <% @future_rentals.each do |rental| %>
          <div class = "my-4">
            <div class="card-product">
              <%= cl_image_tag rental.equipment.photo.key, crop: :fill, class: "product-image" %>
              <div class="card-product-infos">
                <h6><strong>Rental Period:</strong></h6>
                <p><%= "#{rental.start_date.strftime('%d-%b-%Y')} to #{rental.end_date.strftime('%d-%b-%Y')}" %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
          <div class = "my-4">
            <div class="card-product">
              <div class="card-product-infos">
                <h6><strong>You have no upcoming bookings. Book now</strong></h6>
              </div>
            </div>
          </div>
      <% end %>


      <div class = "mb-4">
      <h3>Past Rentals</h3>
      </div>
        <% if @past_rentals.exists? %>
        <% @past_rentals.each do |rental| %>
          <div class = "my-4">
            <div class="card-product">
              <%= cl_image_tag rental.equipment.photo.key, crop: :fill, class: "product-image" %>
              <div class="card-product-infos">
                <h6><strong>Rental Period:</strong></h6>
                <p><%= "#{rental.start_date.strftime('%d-%b-%Y')} to #{rental.end_date.strftime('%d-%b-%Y')}" %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="card-product mb-4">
          <div class="card-product-infos">
            <h6><strong>You have no past bookings. Book now</strong></h6>
          </div>
        </div>
      </div>
    <% end %>

    </div>
</div>

app/views/rentals/new.html.erb
<div class="row">
  <div class="col-6">
    <%= cl_image_tag @equipment.photo.key, crop: :fill, class: 'img-fluid' %>
  </div>
  <div class="col-6">
    <h2 class='mt-3'><strong>Rent <%= @equipment.name %> from <%= @equipment.user.username %></strong></h2>
    <div class='form-login mt-0'>
      <div id='equipment-booking-dates' data-unavailable="<%= @equipment.unavailable_dates.to_json %>">
          <% if current_user.id != @equipment.user_id  %>
             <%= simple_form_for([@equipment, @rental], remote: true ) do |f| %>
                 <%= f.input :start_date, as: :string, type: :text %>
                 <%= f.input :end_date, as: :string, type: :text %>
                 <div> Total Price: $<span id = "total_price">0.00</span> </div>
                 <%= f.submit "Rent", class: "btn btn-primary"%>
              <% end %>
          <% end %>
          <input type="hidden" id="price_per_day" value="<%= @equipment.price_per_day %>">
       </div>
    </div>
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<%= javascript_pack_tag 'total_price', 'data-turbolinks-track': 'reload', defer: true %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <p class=" mb-0">
                  © 2020. Created with love by the CrewCall Team.
                </p>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="d-flex">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://www.flaticon.com/svg/static/icons/svg/2964/2964514.svg" %>
    <% end %>
    <form class="form-inline" action="/equipments">
      <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success mr-sm-2" type="submit">Search</button>
      <% if user_signed_in? %>
        <%= link_to "Add New Equipment", new_equipment_path, class: "btn btn-outline-primary ml-0 mr-2 form-control nav-item", style: "width: auto;" %>
      <% end %>
    </form>
  </div>

    <div class="navbar-nav">
      <div class="nav-item dropdown">
        <% if user_signed_in? %>
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://www.flaticon.com/svg/static/icons/svg/599/599305.svg", crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
            <div class="text-center"><%= current_user.username unless current_user.nil? %></div>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "My Equipments", my_listings_path, class: "dropdown-item" %>
              <%= link_to "My Sales", my_sales_path, class: "dropdown-item" %>
              <%= link_to "My Rentals", rentals_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
          </li>
        <% end %>
      </div>
    </div>
  </div>